// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwNqxKP3WMViDykWKK_H-PQOpPxxbMl8A',
    appId: '1:682523290804:web:15e9a00ef92fe72e4fbbe1',
    messagingSenderId: '682523290804',
    projectId: 'taskmanager-b6548',
    authDomain: 'taskmanager-b6548.firebaseapp.com',
    storageBucket: 'taskmanager-b6548.firebasestorage.app',
    measurementId: 'G-Q2T6SV2846',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKv24cH__vLc0jXq95BydXI9oQ5pCb2K0',
    appId: '1:682523290804:android:88ce097c1e8ddbbb4fbbe1',
    messagingSenderId: '682523290804',
    projectId: 'taskmanager-b6548',
    storageBucket: 'taskmanager-b6548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV8dCQfHlCaq5qxGllg5EoW3wFTRIdFd0',
    appId: '1:682523290804:ios:0d7a4f2d1df1cad24fbbe1',
    messagingSenderId: '682523290804',
    projectId: 'taskmanager-b6548',
    storageBucket: 'taskmanager-b6548.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV8dCQfHlCaq5qxGllg5EoW3wFTRIdFd0',
    appId: '1:682523290804:ios:0d7a4f2d1df1cad24fbbe1',
    messagingSenderId: '682523290804',
    projectId: 'taskmanager-b6548',
    storageBucket: 'taskmanager-b6548.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwNqxKP3WMViDykWKK_H-PQOpPxxbMl8A',
    appId: '1:682523290804:web:8df327c9726dd4774fbbe1',
    messagingSenderId: '682523290804',
    projectId: 'taskmanager-b6548',
    authDomain: 'taskmanager-b6548.firebaseapp.com',
    storageBucket: 'taskmanager-b6548.firebasestorage.app',
    measurementId: 'G-6MRQ41309K',
  );
}
